# Generated by Django 3.0 on 2021-08-08 12:26

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mango',
            old_name='ripe',
            new_name='colored',
        ),
        migrations.RenameField(
            model_name='mango',
            old_name='color',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='mango',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='mango',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mango',
            name='starting_level',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
    ]
