# Generated by Django 3.0 on 2021-08-08 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210808_1226'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mango',
            new_name='Client',
        ),
    ]
